//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPP2
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvailabilitySchedule
    {
        public int Id { get; set; }
        public int CppUserId { get; set; }
        public bool Sunday0 { get; set; }
        public bool Sunday1 { get; set; }
        public bool Sunday2 { get; set; }
        public bool Sunday3 { get; set; }
        public bool Sunday4 { get; set; }
        public bool Sunday5 { get; set; }
        public bool Sunday6 { get; set; }
        public bool Sunday7 { get; set; }
        public bool Sunday8 { get; set; }
        public bool Sunday9 { get; set; }
        public bool Sunday10 { get; set; }
        public bool Sunday11 { get; set; }
        public bool Sunday12 { get; set; }
        public bool Sunday13 { get; set; }
        public bool Sunday14 { get; set; }
        public bool Sunday15 { get; set; }
        public bool Sunday16 { get; set; }
        public bool Sunday17 { get; set; }
        public bool Sunday18 { get; set; }
        public bool Sunday19 { get; set; }
        public bool Sunday20 { get; set; }
        public bool Sunday21 { get; set; }
        public bool Sunday22 { get; set; }
        public bool Sunday23 { get; set; }
        public bool Mon0 { get; set; }
        public bool Mon1 { get; set; }
        public bool Mon2 { get; set; }
        public bool Mon3 { get; set; }
        public bool Mon4 { get; set; }
        public bool Mon5 { get; set; }
        public bool Mon6 { get; set; }
        public bool Mon7 { get; set; }
        public bool Mon8 { get; set; }
        public bool Mon9 { get; set; }
        public bool Mon10 { get; set; }
        public bool Mon11 { get; set; }
        public bool Mon12 { get; set; }
        public bool Mon13 { get; set; }
        public bool Mon14 { get; set; }
        public bool Mon15 { get; set; }
        public bool Mon16 { get; set; }
        public bool Mon17 { get; set; }
        public bool Mon18 { get; set; }
        public bool Mon19 { get; set; }
        public bool Mon20 { get; set; }
        public bool Mon21 { get; set; }
        public bool Mon22 { get; set; }
        public bool Mon23 { get; set; }
        public bool Tue0 { get; set; }
        public bool Tue1 { get; set; }
        public bool Tue2 { get; set; }
        public bool Tue3 { get; set; }
        public bool Tue4 { get; set; }
        public bool Tue5 { get; set; }
        public bool Tue6 { get; set; }
        public bool Tue7 { get; set; }
        public bool Tue8 { get; set; }
        public bool Tue9 { get; set; }
        public bool Tue10 { get; set; }
        public bool Tue11 { get; set; }
        public bool Tue12 { get; set; }
        public bool Tue13 { get; set; }
        public bool Tue14 { get; set; }
        public bool Tue15 { get; set; }
        public bool Tue16 { get; set; }
        public bool Tue17 { get; set; }
        public bool Tue18 { get; set; }
        public bool Tue19 { get; set; }
        public bool Tue20 { get; set; }
        public bool Tue21 { get; set; }
        public bool Tue22 { get; set; }
        public bool Tue23 { get; set; }
        public bool Wed0 { get; set; }
        public bool Wed1 { get; set; }
        public bool Wed2 { get; set; }
        public bool Wed3 { get; set; }
        public bool Wed4 { get; set; }
        public bool Wed5 { get; set; }
        public bool Wed6 { get; set; }
        public bool Wed7 { get; set; }
        public bool Wed8 { get; set; }
        public bool Wed9 { get; set; }
        public bool Wed10 { get; set; }
        public bool Wed11 { get; set; }
        public bool Wed12 { get; set; }
        public bool Wed13 { get; set; }
        public bool Wed14 { get; set; }
        public bool Wed15 { get; set; }
        public bool Wed16 { get; set; }
        public bool Wed17 { get; set; }
        public bool Wed18 { get; set; }
        public bool Wed19 { get; set; }
        public bool Wed20 { get; set; }
        public bool Wed21 { get; set; }
        public bool Wed22 { get; set; }
        public bool Wed23 { get; set; }
        public bool Thu0 { get; set; }
        public bool Thu1 { get; set; }
        public bool Thu2 { get; set; }
        public bool Thu3 { get; set; }
        public bool Thu4 { get; set; }
        public bool Thu5 { get; set; }
        public bool Thu6 { get; set; }
        public bool Thu7 { get; set; }
        public bool Thu8 { get; set; }
        public bool Thu9 { get; set; }
        public bool Thu10 { get; set; }
        public bool Thu11 { get; set; }
        public bool Thu12 { get; set; }
        public bool Thu13 { get; set; }
        public bool Thu14 { get; set; }
        public bool Thu15 { get; set; }
        public bool Thu16 { get; set; }
        public bool Thu17 { get; set; }
        public bool Thu18 { get; set; }
        public bool Thu19 { get; set; }
        public bool Thu20 { get; set; }
        public bool Thu21 { get; set; }
        public bool Thu22 { get; set; }
        public bool Thu23 { get; set; }
        public bool Fri0 { get; set; }
        public bool Fri1 { get; set; }
        public bool Fri2 { get; set; }
        public bool Fri3 { get; set; }
        public bool Fri4 { get; set; }
        public bool Fri5 { get; set; }
        public bool Fri6 { get; set; }
        public bool Fri7 { get; set; }
        public bool Fri8 { get; set; }
        public bool Fri9 { get; set; }
        public bool Fri10 { get; set; }
        public bool Fri11 { get; set; }
        public bool Fri12 { get; set; }
        public bool Fri13 { get; set; }
        public bool Fri14 { get; set; }
        public bool Fri15 { get; set; }
        public bool Fri16 { get; set; }
        public bool Fri17 { get; set; }
        public bool Fri18 { get; set; }
        public bool Fri19 { get; set; }
        public bool Fri20 { get; set; }
        public bool Fri21 { get; set; }
        public bool Fri22 { get; set; }
        public bool Fri23 { get; set; }
        public bool Sat0 { get; set; }
        public bool Sat1 { get; set; }
        public bool Sat2 { get; set; }
        public bool Sat3 { get; set; }
        public bool Sat4 { get; set; }
        public bool Sat5 { get; set; }
        public bool Sat6 { get; set; }
        public bool Sat7 { get; set; }
        public bool Sat8 { get; set; }
        public bool Sat9 { get; set; }
        public bool Sat10 { get; set; }
        public bool Sat11 { get; set; }
        public bool Sat12 { get; set; }
        public bool Sat13 { get; set; }
        public bool Sat14 { get; set; }
        public bool Sat15 { get; set; }
        public bool Sat16 { get; set; }
        public bool Sat17 { get; set; }
        public bool Sat18 { get; set; }
        public bool Sat19 { get; set; }
        public bool Sat20 { get; set; }
        public bool Sat21 { get; set; }
        public bool Sat22 { get; set; }
        public bool Sat23 { get; set; }
    
        public virtual CppUser CppUser { get; set; }
    }
}
