//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPP2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public int Id { get; set; }
        public int CppUserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public byte[] Photo { get; set; }
        public int Age { get; set; }
        public string PrimaryLanguge { get; set; }
        public string LanguageLearning { get; set; }
        public Nullable<decimal> AverageRating { get; set; }
        public int SpeakingAbility { get; set; }
        public int ComprehensionAbility { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string TimeZoneCode { get; set; }
        public int Desired_Hours { get; set; }
        public string Interest1 { get; set; }
        public string Interest2 { get; set; }
        public string Interest3 { get; set; }
        public string Interest4 { get; set; }
        public string Interest5 { get; set; }
        public string PreferredGender { get; set; }
    
        public virtual CppUser CppUser { get; set; }
    }
}
