//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPP2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduledSession
    {
        public int Id { get; set; }
        public int CppUserId { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public byte[] EndTime { get; set; }
    
        public virtual CppUser CppUser { get; set; }
    }
}
