//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPP2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionLog
    {
        public int Id { get; set; }
        public int CallSenderId { get; set; }
        public System.TimeSpan SessionBegin { get; set; }
        public Nullable<System.TimeSpan> SessionEnd { get; set; }
        public int CallReceiverId { get; set; }
        public string SessionString { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual CppUser CppUser { get; set; }
        public virtual CppUser CppUser1 { get; set; }
    }
}
